version: "3.3"

services:
    wine-box:
        image: "chisbread/wine-box:latest"
        restart: unless-stopped
        container_name: "wine-box"
        environment:
            PAYLOADS: 1
            GID: 1000
            UID: 1000
        ports:
            - "8080:8080"
        volumes:
            - "/home/bread/external:/home/app/external"
        tty: true
